import {
  Activity,
  Baby,
  Banknote,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Car,
  Cat,
  Clapperboard,
  Coffee,
  Coins,
  CreditCard,
  Dog,
  Droplet,
  Dumbbell,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  Headphones,
  Heart,
  HeartPulse,
  Hotel,
  House,
  Landmark,
  Lightbulb,
  type LucideIcon,
  Luggage,
  Map as MapIcon,
  MapPin,
  Music,
  PartyPopper,
  PawPrint,
  Percent,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Scissors,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Stethoscope,
  Tag,
  Ticket,
  TrainFront,
  TrendingUp,
  Tv,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from "lucide-react";

/** Curated lucide icons selectable for a category (keyed by their lucide name), grouped by theme. */
const REGISTRY: Record<string, LucideIcon> = {
  // Food & drink
  "utensils-crossed": UtensilsCrossed,
  utensils: Utensils,
  coffee: Coffee,
  wine: Wine,
  beer: Beer,
  pizza: Pizza,
  "shopping-cart": ShoppingCart,
  // Transport
  car: Car,
  bus: Bus,
  fuel: Fuel,
  bike: Bike,
  plane: Plane,
  "train-front": TrainFront,
  // Home & utilities
  house: House,
  sofa: Sofa,
  lightbulb: Lightbulb,
  droplet: Droplet,
  zap: Zap,
  flame: Flame,
  wifi: Wifi,
  smartphone: Smartphone,
  // Health
  "heart-pulse": HeartPulse,
  pill: Pill,
  stethoscope: Stethoscope,
  dumbbell: Dumbbell,
  activity: Activity,
  // Education
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  // Leisure
  "gamepad-2": Gamepad2,
  film: Film,
  music: Music,
  tv: Tv,
  headphones: Headphones,
  ticket: Ticket,
  clapperboard: Clapperboard,
  // Travel
  luggage: Luggage,
  hotel: Hotel,
  "map-pin": MapPin,
  map: MapIcon,
  // Shopping & beauty
  "shopping-bag": ShoppingBag,
  shirt: Shirt,
  gem: Gem,
  scissors: Scissors,
  sparkles: Sparkles,
  // Pets
  dog: Dog,
  cat: Cat,
  "paw-print": PawPrint,
  // Gifts & celebration
  gift: Gift,
  "party-popper": PartyPopper,
  cake: Cake,
  // Finance
  "piggy-bank": PiggyBank,
  landmark: Landmark,
  receipt: Receipt,
  "credit-card": CreditCard,
  wallet: Wallet,
  banknote: Banknote,
  coins: Coins,
  "trending-up": TrendingUp,
  percent: Percent,
  "shield-check": ShieldCheck,
  // Work & maintenance
  briefcase: Briefcase,
  "building-2": Building2,
  wrench: Wrench,
  // People & family
  users: Users,
  baby: Baby,
  heart: Heart,
  // Default
  tag: Tag,
};

/** The icon names offered in the category picker, in display order. */
export const CATEGORY_ICON_NAMES = Object.keys(REGISTRY);

export const DEFAULT_CATEGORY_ICON = "tag";

/** Render a category's lucide icon by name, falling back to a generic tag. */
export function CategoryIcon({ name, size = 16 }: { name: string; size?: number }) {
  const Icon = REGISTRY[name] ?? Tag;
  return <Icon size={size} />;
}
