import {
  ArrowDown,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpRight,
  Ban,
  Bell,
  Briefcase,
  Building2,
  Calendar,
  CalendarClock,
  CalendarRange,
  CalendarX,
  Car,
  CarFront,
  ChartPie,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  CircleCheck,
  CreditCard,
  Download,
  Ellipsis,
  Eye,
  EyeOff,
  FileDown,
  FileMinus,
  FileSpreadsheet,
  FileText,
  FileUp,
  Fingerprint,
  GraduationCap,
  HandCoins,
  Handshake,
  HeartPulse,
  HelpCircle,
  House,
  Info,
  Landmark,
  Layers,
  LayoutDashboard,
  ListX,
  LoaderCircle,
  Lock,
  LogOut,
  type LucideIcon,
  Mail,
  Menu,
  PartyPopper,
  Pencil,
  PiggyBank,
  PlugZap,
  Plus,
  Receipt,
  RefreshCw,
  Repeat,
  RotateCcw,
  Scale,
  Search,
  SearchX,
  Send,
  Settings,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Tag,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Unplug,
  User,
  UserPlus,
  Users,
  UtensilsCrossed,
  Wallet,
  X,
} from "lucide-react";
import type { CSSProperties } from "react";
import { CATEGORY_ICON_COMPONENTS } from "./category-icon";

/** Maps the prototype's lucide icon-name strings to lucide-react components. */
const ICONS: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  wallet: Wallet,
  "credit-card": CreditCard,
  "arrow-left-right": ArrowLeftRight,
  "arrow-up-right": ArrowUpRight,
  "arrow-down-left": ArrowDownLeft,
  "arrow-down": ArrowDown,
  calendar: Calendar,
  "calendar-range": CalendarRange,
  "calendar-clock": CalendarClock,
  "calendar-x": CalendarX,
  users: Users,
  "chart-pie": ChartPie,
  settings: Settings,
  "chevrons-up-down": ChevronsUpDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  sparkles: Sparkles,
  search: Search,
  bell: Bell,
  plus: Plus,
  house: House,
  menu: Menu,
  eye: Eye,
  "eye-off": EyeOff,
  check: Check,
  "check-circle": CircleCheck,
  x: X,
  pencil: Pencil,
  "refresh-cw": RefreshCw,
  "rotate-ccw": RotateCcw,
  repeat: Repeat,
  layers: Layers,
  info: Info,
  scale: Scale,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "trash-2": Trash2,
  download: Download,
  "arrow-right": ArrowRight,
  mail: Mail,
  lock: Lock,
  smartphone: Smartphone,
  "loader-circle": LoaderCircle,
  "search-x": SearchX,
  "file-minus": FileMinus,
  "list-x": ListX,
  "triangle-alert": TriangleAlert,
  "alert-triangle": TriangleAlert,
  handshake: Handshake,
  "hand-coins": HandCoins,
  landmark: Landmark,
  ban: Ban,
  unplug: Unplug,
  receipt: Receipt,
  "building-2": Building2,
  target: Target,
  "piggy-bank": PiggyBank,
  "file-text": FileText,
  "file-down": FileDown,
  "file-up": FileUp,
  "file-spreadsheet": FileSpreadsheet,
  fingerprint: Fingerprint,
  briefcase: Briefcase,
  "log-out": LogOut,
  send: Send,
  user: User,
  "user-plus": UserPlus,
  ellipsis: Ellipsis,
  tag: Tag,
  // category icons
  "utensils-crossed": UtensilsCrossed,
  car: Car,
  "car-front": CarFront,
  "party-popper": PartyPopper,
  "shopping-bag": ShoppingBag,
  "heart-pulse": HeartPulse,
  "plug-zap": PlugZap,
  "graduation-cap": GraduationCap,
};

/** Renders a lucide icon by the prototype's name string (1:1 port of the prototype's <Icon>). */
export function Icon({
  name,
  size = 18,
  sw = 1.9,
  className,
  style,
}: {
  name: string;
  size?: number;
  sw?: number;
  className?: string;
  style?: CSSProperties;
}) {
  // Fall back to the category-icon set (its names aren't all in ICONS) before the "?" glyph,
  // so a category's icon renders correctly anywhere it's shown via the generic <Icon>.
  const Cmp = ICONS[name] ?? CATEGORY_ICON_COMPONENTS[name] ?? HelpCircle;
  return <Cmp size={size} strokeWidth={sw} className={className} style={style} aria-hidden="true" />;
}
