import {
  ArrowDown,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowUpRight,
  Ban,
  Bell,
  Building2,
  CalendarClock,
  CalendarRange,
  CalendarX,
  Car,
  CarFront,
  ChartPie,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  CreditCard,
  Ellipsis,
  Eye,
  EyeOff,
  FileDown,
  FileSpreadsheet,
  FileText,
  GraduationCap,
  Handshake,
  HeartPulse,
  HelpCircle,
  House,
  Info,
  Landmark,
  Layers,
  LayoutDashboard,
  type LucideIcon,
  Menu,
  PartyPopper,
  Pencil,
  PiggyBank,
  PlugZap,
  Plus,
  Receipt,
  RefreshCw,
  Repeat,
  Scale,
  Search,
  Settings,
  ShoppingBag,
  Sparkles,
  Tag,
  Target,
  TrendingUp,
  TriangleAlert,
  Unplug,
  Users,
  UtensilsCrossed,
  Wallet,
  X,
} from "lucide-react";
import type { CSSProperties } from "react";

/** Maps the prototype's lucide icon-name strings to lucide-react components. */
const ICONS: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  wallet: Wallet,
  "credit-card": CreditCard,
  "arrow-left-right": ArrowLeftRight,
  "arrow-up-right": ArrowUpRight,
  "arrow-down-left": ArrowDownLeft,
  "arrow-down": ArrowDown,
  "calendar-range": CalendarRange,
  "calendar-clock": CalendarClock,
  "calendar-x": CalendarX,
  users: Users,
  "chart-pie": ChartPie,
  settings: Settings,
  "chevrons-up-down": ChevronsUpDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  sparkles: Sparkles,
  search: Search,
  bell: Bell,
  plus: Plus,
  house: House,
  menu: Menu,
  eye: Eye,
  "eye-off": EyeOff,
  check: Check,
  x: X,
  pencil: Pencil,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  layers: Layers,
  info: Info,
  scale: Scale,
  "trending-up": TrendingUp,
  "triangle-alert": TriangleAlert,
  "alert-triangle": TriangleAlert,
  handshake: Handshake,
  landmark: Landmark,
  ban: Ban,
  unplug: Unplug,
  receipt: Receipt,
  "building-2": Building2,
  target: Target,
  "piggy-bank": PiggyBank,
  "file-text": FileText,
  "file-down": FileDown,
  "file-spreadsheet": FileSpreadsheet,
  ellipsis: Ellipsis,
  tag: Tag,
  // category icons
  "utensils-crossed": UtensilsCrossed,
  car: Car,
  "car-front": CarFront,
  "party-popper": PartyPopper,
  "shopping-bag": ShoppingBag,
  "heart-pulse": HeartPulse,
  "plug-zap": PlugZap,
  "graduation-cap": GraduationCap,
};

/** Renders a lucide icon by the prototype's name string (1:1 port of the prototype's <Icon>). */
export function Icon({
  name,
  size = 18,
  sw = 1.9,
  className,
  style,
}: {
  name: string;
  size?: number;
  sw?: number;
  className?: string;
  style?: CSSProperties;
}) {
  const Cmp = ICONS[name] ?? HelpCircle;
  return <Cmp size={size} strokeWidth={sw} className={className} style={style} aria-hidden="true" />;
}
